### PR TITLE
remove pods and update readme

### PR DESCRIPTION
**Pull request by eduedix**

### CODE REVIEW

**Comment by gaston23** [comment]
I trust you :)

**Comment by eduedix** [comment]
thx for the merge. Can you please sync the version in npm with github?

**Comment by gaston23** [comment]
Can that be automated or can I give you access to you to publish that? Thanks

**Comment by eduedix** [comment]
I guess there is no automated way to do this.

**Comment by gaston23** [comment]
I think I updated it. Please check and let me know

**Comment by eduedix** [comment]
seems fine.

**Comment by eduedix** [comment]
do you have any plans to develop for android as well?

**Pull request merged**
